name: ssev_analytics
channels:
- conda-forge
- nodefaults
dependencies:
- python==3.9
- pillow==9.2.0
- scipy==1.9.0
- cython==0.29.32
- matplotlib==3.5.2
- pandas==1.4.3
- numpy==1.23.1
- pymongo==4.2.0
- requests==2.28.1
- plotly==5.9.0
- statsmodels==0.13.2
- scikit-learn==1.1.1
- jupyter==1.0.0
- pip==22.2.1
- pip:
  - git+https://github.com/jxx123/fireTS.git